apiVersion: v1
kind: Service
metadata:
  name: sentiment-service
  labels:
    app: sentiment-service
spec:
  type: LoadBalancer
  selector:
    app: sentiment-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
